version: '2'

services:
  db:
    image: postgres
    volumes:
      - .:/app
      - db:/var/lib/postgresql/data
    expose:
      - '5432'

  test: &test
    image: crystallang/crystal
    volumes:
      - .:/app
    links:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres@db/imdb_test
    working_dir: /app
    command: "crystal spec --fail-fast"

  web:
    <<: *test
    environment:
      - DATABASE_URL=postgresql://postgres@db/imdb
      - PORT=4000
    ports:
      - "4000:4000"
    command: "crystal run ./src/crystal_demo.cr"

  prod:
    <<: *test
    environment:
      - DATABASE_URL=postgresql://postgres@db/imdb
      - PORT=4001
    ports:
      - "4001:4001"
    command: bash -c "crystal build --release -s src/crystal_demo.cr -o bin/app && ./bin/app"

  heroku:
    build:
      context: .
      dockerfile: Dockerfile.heroku
    volumes:
      - .:/app
      - heroku:/root
    working_dir: /app

volumes:
  db:
  heroku:
